package bot

// boxQuotes is the pool of random quotes for the /is_the_box_up command.
// Add, remove, or reorder entries as you like.
var boxQuotes = []string{
	"BROTHER, I AM PINNED HERE.",
	"ALPHARIUS.",
	"BY THE WILL OF THE OMNISSIAH, FUCK OFF.",
	"I WILL BURN THIS UNIT DOWN.",
	"BANNED.",
	"THE 101ST'S BOX IS UP.",
	"LIB WHEN?",
	"TAKE A WILD FUCKING GUESS.",
	"YES.",
	"NO.",
	"MAYBE.",
	"YOU CAN USE /PING.",
	"NO. BUT THE DOW IS AT 50K.",
	"60% OF THE TIME, IT WORKS EVERY TIME.",
	"GRIM'S GONE FOR A CIGARETTE.",
	"DID YOU READ THE MANUAL?",
	"THE BOX IS DOWN.",
	"THE BOX IS UP.",
	"UPTIME: BETTER THAN NOTHING.",
	"THERE IS NO BOX.",
	"WHAT?",
	"DO YOU REALLY WANT TO KNOW?",
	"KIND OF.",
	"SOMETIMES.",
	"NOT TODAY.",
	"IT'S MY BIRTHDAY. NO.",
	"ABSOLUTELY.",
	"ABSOLUTELY NOT.",
	"TOUCH GRASS.",
	"ASK PICKER.",
	"I'LL MAKE MY OWN BOX, WITH BLACKJACK AND HOOKERS.",
	"GODS I WAS STRONG THEN!",
	"STOP THIS MADNESS IN THE NAME OF YOUR KING!",
	`The missile knows where it is at all times. It knows this because it knows where it isn't. By subtracting where it is from where it isn't, or where it isn't from where it is (whichever is greater), it obtains a difference, or deviation. The guidance subsystem uses deviations to generate corrective commands to drive the missile from a position where it is to a position where it isn't, and arriving at a position where it wasn't, it now is. Consequently, the position where it is, is now the position that it wasn't, and it follows that the position that it was, is now the position that it isn't. In the event that the position that it is in is not the position that it wasn't, the system has acquired a variation, the variation being the difference between where the missile is, and where it wasn't. If variation is considered to be a significant factor, it too may be corrected by the GEA. However, the missile must also know where it was. The missile guidance computer scenario works as follows. Because a variation has modified some of the information the missile has obtained, it is not sure just where it is. However, it is sure where it isn't, within reason, and it knows where it was. It now subtracts where it should be from where it wasn't, or vice-versa, and by differentiating this from the algebraic sum of where it shouldn't be, and where it was, it is able to obtain the deviation and its variation, which is called error.`,
}
